BigBasket/clp

components/compression-job-handler/compression_job_handler/compression_job_handler.py
components/compression-job-handler/requirements.txt

BB-154080 Added code to acquire lock on lock file

---

components/compression-job-handler/compression_job_handler/compression_job_handler.py

BB-154080 Added exit point to code

---

components/core/src/clg/CommandLineArguments.hpp
components/core/src/clg/clg.cpp

BB-154080 Fixed get_archive_path function

---

components/core/src/clo/clo.cpp

BB-154080 Fixed typo

---

components/search-job-handler/search_job_handler/search_job_handler.py

BB-154080: running db monitor in the same process

---

components/search-job-handler/search_job_handler/search_job_handler.py

BB-154080: added futures

---

components/search-job-handler/search_job_handler/search_job_handler.py

BB-154080: corrected

---

components/search-job-handler/search_job_handler/search_job_handler.py

BB-154080: added futrue

---

components/search-job-handler/search_job_handler/search_job_handler.py

BB-154080: corrected the fut

---

.gitignore
components/search-job-handler/search_job_handler/search_job_handler.py

BB-154080: added futru

---

components/search-job-handler/search_job_handler/search_job_handler.py

BB-154080: removed main from async

---

components/search-job-handler/search_job_handler/search_job_handler.py

BB-154080: revert

---

components/search-job-handler/search_job_handler/search_job_handler.py

BB-154080: added args

---

components/search-job-handler/search_job_handler/search_job_handler.py

BB-154080: removed async

---

components/search-job-handler/search_job_handler/search_job_handler.py

BB-154080: hack

---

components/search-job-handler/search_job_handler/search_job_handler.py

changed pagination limit

---

components/search-job-handler/search_job_handler/search_job_handler.py

BH-623 Added absolute context feature

---

components/core/src/Grep.cpp

BH-685 Send only log as result in clg

---

components/core/src/Grep.cpp

BH-685 Strip timestamp in log before sending in clg

---

components/core/src/clg/CommandLineArguments.cpp
components/core/src/clg/clg.cpp

BH-685 Fixed typo

---

components/core/src/clg/clg.cpp

BH-685 Fixed error
